proxy-dns: true
proxy-dns-port: 5153
proxy-dns-address: 127.0.0.1
proxy-dns-upstream:
 - https://1.1.1.1/dns-query
 - https://1.0.0.1/dns-query
 - https://2606:4700:4700::1111/dns-query 
 - https://2606:4700:4700::1001/dns-query
